"""Advanced labs: PowerShell automation, IIS/debugging, and interview prep exercises."""

ADVANCED_LABS = {
    "powershell_lab": {
        "id": "powershell_lab",
        "name": "PowerShell Automation Lab",
        "domain": "powershell",
        "description": "Practice PowerShell scripts for enterprise admin: certificate management, service monitoring, log parsing, automated reporting.",
        "exercises": [
            {
                "id": "ps_1",
                "title": "Check SSL Certificate Expiration",
                "instruction": "Write a PowerShell script that checks all SSL certificates in the LocalMachine\\My store and returns any expiring within 30 days. Include the Subject, NotAfter date, and Thumbprint.",
                "expected_answer": "$threshold = (Get-Date).AddDays(30)\n$expiring = Get-ChildItem Cert:\\LocalMachine\\My |\n    Where-Object { $_.NotAfter -lt $threshold -and $_.NotAfter -gt (Get-Date) } |\n    Select-Object Subject, NotAfter, Thumbprint\n\nif ($expiring) {\n    Write-Warning \"Certificates expiring within 30 days:\"\n    $expiring | Format-Table -AutoSize\n} else {\n    Write-Host \"No certificates expiring within 30 days.\" -ForegroundColor Green\n}",
                "explanation": "Certificate expiry monitoring prevents integration outages (like T4: TCIC/NCIC warrant interface). The script checks the LocalMachine\\My certificate store, which is where server certificates are typically installed. The 30-day threshold gives enough time to renew before expiration. In production, this would be a scheduled task that sends email alerts.",
                "tip": "Cert:\\LocalMachine\\My is the standard Windows certificate store for server certificates. Cert:\\CurrentUser\\My is for user certificates. Always check both if you're not sure where certs are installed."
            },
            {
                "id": "ps_2",
                "title": "Parse IIS Log for Error Status Codes",
                "instruction": "Write a PowerShell script that reads an IIS log file, counts HTTP status codes 4xx and 5xx, and shows the top 5 most frequent error URLs.",
                "expected_answer": "# Parse IIS W3C format log\n$logPath = 'C:\\inetpub\\logs\\LogFiles\\W3SVC1\\u_ex260225.log'\n$lines = Get-Content $logPath | Where-Object { $_ -notmatch '^#' }\n\n$errors = $lines | ForEach-Object {\n    $fields = $_ -split ' '\n    [PSCustomObject]@{\n        Date = $fields[0]\n        Time = $fields[1]\n        Method = $fields[3]\n        URI = $fields[4]\n        Status = [int]$fields[11]\n    }\n} | Where-Object { $_.Status -ge 400 }\n\nWrite-Host \"Error Summary:\" -ForegroundColor Yellow\n$errors | Group-Object Status | Sort-Object Count -Descending |\n    Format-Table @{N='Status';E={$_.Name}}, Count -AutoSize\n\nWrite-Host \"`nTop 5 Error URLs:\" -ForegroundColor Yellow\n$errors | Group-Object URI | Sort-Object Count -Descending |\n    Select-Object -First 5 |\n    Format-Table @{N='URL';E={$_.Name}}, Count -AutoSize",
                "explanation": "IIS log analysis is a core skill for application support. When users report application errors, the IIS log tells you exactly which URLs are failing and with what status codes. 4xx = client errors (404 Not Found, 401 Unauthorized, 403 Forbidden). 5xx = server errors (500 Internal Server Error, 503 Service Unavailable). Grouping by URI shows which endpoints are failing most frequently.",
                "tip": "IIS logs are in W3C Extended format by default. Fields vary by configuration — always check the #Fields header line to know which column is which. Common gotcha: the fields are space-separated but some contain spaces (like user agent) — use proper CSV parsing for production scripts."
            },
            {
                "id": "ps_3",
                "title": "Automated Service Health Check",
                "instruction": "Write a PowerShell script that checks if specific Windows services are running (W3SVC for IIS, MSSQLSERVER for SQL Server, CeleryWorker for background jobs). If any are stopped, attempt to start them and log the result.",
                "expected_answer": "$services = @('W3SVC', 'MSSQLSERVER', 'CeleryWorker')\n$logFile = \"C:\\Logs\\service_check_$(Get-Date -Format 'yyyyMMdd_HHmmss').log\"\n\nforeach ($svcName in $services) {\n    $svc = Get-Service -Name $svcName -ErrorAction SilentlyContinue\n    if (-not $svc) {\n        \"$svcName - NOT FOUND\" | Tee-Object -FilePath $logFile -Append\n        continue\n    }\n    if ($svc.Status -eq 'Running') {\n        \"$svcName - RUNNING (OK)\" | Tee-Object -FilePath $logFile -Append\n    } else {\n        \"$svcName - STOPPED — attempting restart...\" | Tee-Object -FilePath $logFile -Append\n        try {\n            Start-Service $svcName -ErrorAction Stop\n            \"$svcName - RESTARTED SUCCESSFULLY\" | Tee-Object -FilePath $logFile -Append\n        } catch {\n            \"$svcName - RESTART FAILED: $($_.Exception.Message)\" | Tee-Object -FilePath $logFile -Append\n        }\n    }\n}\n\nWrite-Host \"Log saved: $logFile\"",
                "explanation": "Service monitoring is a daily operational task. This script checks the three most common services in a municipal web application environment: IIS (web server), SQL Server (database), and background workers (Celery/scheduled tasks). The script attempts auto-remediation (restart) and logs everything for audit purposes. In production, this would be scheduled via Task Scheduler to run every 5 minutes.",
                "tip": "Always use -ErrorAction SilentlyContinue when checking services that might not exist on all servers. Use Tee-Object to both display output AND write to a log file simultaneously."
            },
        ],
    },
    "debugging_advanced_lab": {
        "id": "debugging_advanced_lab",
        "name": "Advanced Debugging Lab",
        "domain": "debugging",
        "description": "Practice systematic debugging: reproduce issues, read stack traces, analyze logs, isolate root causes, document defects.",
        "exercises": [
            {
                "id": "dbg_adv_1",
                "title": "Read a .NET Stack Trace",
                "instruction": "Given this stack trace from a Tyler Incode crash, identify: (1) the exception type, (2) the exact line where the error occurred, (3) the likely root cause, and (4) what you'd check first.\n\nSystem.NullReferenceException: Object reference not set to an instance of an object.\n   at Incode.Court.Services.PaymentService.PostPayment(Payment payment) in PaymentService.cs:line 142\n   at Incode.Court.Controllers.PaymentController.ProcessOnlinePayment(PaymentRequest request) in PaymentController.cs:line 87\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.Execute()\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)",
                "expected_answer": "(1) Exception type: System.NullReferenceException — a variable was null when code tried to use it.\n\n(2) Exact error location: PaymentService.cs, line 142, inside the PostPayment method. The call originated from PaymentController.cs line 87 (ProcessOnlinePayment).\n\n(3) Likely root cause: The 'payment' parameter or one of its properties (e.g., payment.CaseNumber, payment.Amount, payment.GatewayResponse) is null. This commonly happens when:\n   - The online payment request is missing a required field\n   - The gateway response didn't include expected data\n   - A database lookup (e.g., finding the case) returned null\n\n(4) What to check first:\n   - Review the HTTP request body that triggered this — is any field null?\n   - Check PaymentService.cs line 142 — which object is being dereferenced?\n   - Check if the case_number in the payment exists in the database\n   - Check the gateway response for the transaction — did it return complete data?",
                "explanation": "Reading stack traces is the #1 debugging skill for enterprise application support. The stack trace reads bottom-to-top: the bottom is where the request entered the system (routing middleware), and the top is where the error occurred. NullReferenceException means code tried to access a property or method on a null object. The file name and line number tell you exactly where to look. In support (where you may not have access to source code), you focus on: what method was called, what parameters it takes, and what could be null.",
                "tip": "Stack traces read from bottom (entry point) to top (crash point). The most important line is the TOP of the stack — that's where the error actually happened. The lines below it show how the code got there. In production support, you often don't have the source code — but the method names and parameter types tell you a lot about what the code was trying to do."
            },
            {
                "id": "dbg_adv_2",
                "title": "Write a Root Cause Analysis",
                "instruction": "You resolved an incident where Maximo work orders weren't generating (the M1 scenario). Write a formal Root Cause Analysis (RCA) document with: Problem Statement, Timeline, Root Cause, Contributing Factors, Resolution, and Preventive Actions.",
                "expected_answer": "ROOT CAUSE ANALYSIS\n\nIncident: INC-2026-0147\nDate: 2026-02-25\nSeverity: Critical (P1)\nSystem: IBM Maximo — Preventive Maintenance\n\nPROBLEM STATEMENT\n47 preventive maintenance work orders failed to generate for Water Utility fleet and pump equipment over a 3-day period, creating compliance and safety risk for critical infrastructure.\n\nTIMELINE\n- Day 1 (Feb 22): PMWOGen cron task last successful run at 02:00\n- Day 1 (Feb 22, 02:15): PMWOGen fails with BMXAA4211E duplicate key error\n- Days 2-3: Cron task continues to fail each scheduled run\n- Day 3 (Feb 25, 08:30): Water Utility supervisor reports missing work orders\n- Day 3 (Feb 25, 09:00): Applications team begins investigation\n- Day 3 (Feb 25, 10:30): Root cause identified and fix applied\n- Day 3 (Feb 25, 11:00): All 47 PMs generated successfully\n\nROOT CAUSE\nPM record PM-1003 referenced asset FL-1003 (2018 International Dump Truck), which had been decommissioned on Feb 20 but the associated PM was not deactivated. The PMWOGen cron task processes all active PMs in a single batch — when it attempted to generate a work order for a decommissioned asset, it threw a duplicate key error (BMXAA4211E) that crashed the entire batch.\n\nCONTRIBUTING FACTORS\n1. No validation exists between asset decommissioning and PM deactivation\n2. PMWOGen does not have per-record error handling — one bad record stops all processing\n3. No monitoring alert for PMWOGen failures — 3 days passed before detection\n\nRESOLUTION\n1. Deactivated PM-1003 (orphaned PM on decommissioned asset)\n2. Validated all other PM-to-asset relationships — no additional issues found\n3. Restarted PMWOGen cron task — all 47 overdue PMs generated\n\nPREVENTIVE ACTIONS\n1. CR-2026-0089: Add asset status validation to PM activation/deactivation workflow\n2. Implement automated monitoring alert for PMWOGen failures (notify within 1 hour)\n3. Add quarterly audit: check for active PMs on non-operating assets\n4. Request Maximo enhancement: per-record error handling in PMWOGen (logged with IBM)",
                "explanation": "A Root Cause Analysis (RCA) is a formal document that answers: What happened? Why? How do we prevent it? The format follows a standard structure used across industries. The key sections are: (1) clear problem statement with business impact, (2) precise timeline showing when things went wrong and when they were detected, (3) technical root cause explanation, (4) contributing factors (what made it worse or allowed it to happen), and (5) specific, actionable preventive measures. RCAs are required for P1/P2 incidents in most enterprise IT organizations.",
                "tip": "Contributing factors are as important as the root cause. The root cause is WHY it broke. Contributing factors are WHY it took 3 days to detect, WHY the blast radius was 47 PMs instead of 1, and WHY the process allowed an orphaned PM to exist. Good preventive actions address the root cause AND all contributing factors."
            },
        ],
    },
    "interview_prep_lab": {
        "id": "interview_prep_lab",
        "name": "Interview Preparation Lab",
        "domain": "requirements",
        "description": "Practice translating technical work into interview-ready answers. STAR format, behavioral questions, and technical scenarios.",
        "exercises": [
            {
                "id": "int_prep_1",
                "title": "Answer: 'Tell me about a time you resolved a critical system outage'",
                "instruction": "Using the STAR method, write an answer based on the T4 scenario (Tyler Incode TCIC/NCIC warrant interface failure). The interviewer is a non-technical hiring manager for a municipal IT department. Keep it under 2 minutes spoken length (~250 words).",
                "expected_answer": "In my role supporting municipal court systems, our nightly warrant upload to the state crime database — TCIC/NCIC — failed one morning. This was a public safety issue because officers in the field couldn't verify warrants during traffic stops.\n\nMy task was to diagnose the failure and restore the connection as quickly as possible while keeping court operations informed.\n\nI started by reviewing the error logs, which showed an SSL authentication failure. I checked the client certificate we use for the secure connection to the state system and found it had expired the day before. No one had been tracking the expiration date.\n\nI generated a new certificate, submitted it to the Department of Public Safety for approval, and once signed, I installed it on our server and updated the court system's configuration. I then reprocessed all 15 warrants that had been stuck and confirmed with DPS that they received them.\n\nThe result was that the warrant system was restored within 4 hours. But more importantly, I implemented a monitoring script that alerts our team 30 days before any certificate expires. Since then, we haven't had a single certificate-related outage. I also created a step-by-step runbook so any team member can handle the renewal process.\n\nThis experience reinforced the importance of proactive monitoring — it's always better to prevent an outage than to respond to one.",
                "explanation": "This answer demonstrates: (1) Technical competency — SSL/TLS, certificates, PowerShell. (2) Business awareness — understood the public safety impact. (3) Communication — kept stakeholders informed. (4) Process improvement — didn't just fix it, prevented recurrence. (5) Documentation — created a runbook for the team. The non-technical hiring manager hears: you're competent, calm under pressure, and you improve processes.",
                "tip": "For non-technical interviewers: emphasize the IMPACT (public safety risk) and the IMPROVEMENT (monitoring script). For technical interviewers: emphasize the DIAGNOSTIC PROCESS (how you found the root cause) and the TECHNICAL SOLUTION (certificate generation, mTLS). Same story, different emphasis."
            },
            {
                "id": "int_prep_2",
                "title": "Answer: 'How do you approach a report that shows wrong numbers?'",
                "instruction": "Using the T2 scenario (payment reconciliation mismatch) and T5 scenario (court statistics missing dismissed cases), describe your systematic approach to report debugging. Frame it as a methodology, not just a story.",
                "expected_answer": "When I'm told a report shows wrong numbers, I follow a five-step methodology that I've developed through experience:\n\nFirst, I QUANTIFY the gap. I get the exact expected number and actual number from the person who noticed the discrepancy. A vague 'it looks wrong' needs to become '$340 difference' or '15% fewer dispositions.'\n\nSecond, I BREAK IT DOWN. I run the report query at a more granular level — by category, by date, by status — to narrow down which segment has the gap. This is like a binary search in debugging.\n\nThird, I COMPARE the source. I pull data directly from the database tables (bypassing the report's stored procedure) and compare totals. If the raw data matches the expected number, the bug is in the report logic. If it doesn't, the data itself is wrong.\n\nFourth, I INSPECT the query logic. I read the stored procedure line by line, looking for the three most common bugs: wrong JOIN types (INNER vs LEFT), missing status values in WHERE/IN clauses, and NULL handling issues.\n\nFifth, I PROVE the fix. I don't just fix the query — I run it for historical periods and verify every result matches known good data. Then I document the root cause and update the report specification.\n\nFor example, I once found a $340 payment variance caused by a business rule rejecting warrant-status payments, and another time found 15% missing dispositions because the query only checked one status instead of all terminal statuses.",
                "explanation": "This answer showcases METHODOLOGY — it shows the interviewer you have a repeatable, systematic process, not just one lucky fix. The five steps (Quantify, Break Down, Compare, Inspect, Prove) form a framework that applies to ANY report discrepancy. The two real examples at the end prove you've actually done this. This is the kind of answer that separates a senior analyst from a junior one.",
                "tip": "Interviewers love FRAMEWORKS. Instead of just telling a story, show that you have a systematic approach. Name the steps. Then give 1-2 examples to prove you've applied it. This works for any 'how do you approach X' question."
            },
        ],
    },
}
