"""20 enterprise legacy system scenarios with full teaching content.

Each scenario models a realistic incident/task an IT Applications Analyst III
would handle at a municipality using IBM Maximo, Tyler Incode, and e-Builder.
"""

ENTERPRISE_SCENARIOS = {

    # ================================================================
    #  IBM MAXIMO SCENARIOS (M1-M7)
    # ================================================================

    "maximo_pm_failure": {
        "name": "M1: Maximo PM Work Order Generation Failure",
        "system": "maximo",
        "description": "PMWOGen cron task stopped generating preventive maintenance work orders for Water Utility fleet. 47 PMs are past due.",
        "phases": ["investigation", "root_cause", "resolution"],
        "tasks": [
            {
                "title": "M1: Investigate PMWOGen Cron Task Failure",
                "domain": "infrastructure",
                "business_context": "Water Utility supervisor reports that 47 preventive maintenance work orders were not generated overnight. Fleet vehicles and pump equipment are missing their scheduled maintenance, creating compliance and safety risk.",
                "description": "Check the PMWOGen cron task status, review the cron task log, identify why PM work orders stopped generating.",
                "evidence_reviewed": "Maximo Cron Task Setup shows PMWOGEN last ran 3 days ago. System log shows: 'BMXAA4211E - Database error number 2601 has occurred when operating on WOACTIVITY.' Three PM records have NEXTDATE in the past. Asset FL-1003 status is DECOMMISSIONED but PM-1003 is still ACTIVE.",
                "decision_made": "Root cause: PM-1003 references a decommissioned asset (FL-1003), causing a duplicate key error that crashes the entire PMWOGen batch. The cron task fails on the first error and does not process remaining PMs.",
                "technical_detail": "-- Check cron task status\nSELECT crontaskname, active, lastrun, nextrun\nFROM mx_crontaskdef\nWHERE crontaskname = 'PMWOGEN';\n\n-- Find PMs with overdue next dates\nSELECT p.pmnum, p.description, p.assetnum, p.nextdate, p.status,\n       a.status AS asset_status\nFROM mx_pm p\nLEFT JOIN mx_asset a ON p.assetnum = a.assetnum\nWHERE p.status = 'ACTIVE' AND p.nextdate < CURRENT_DATE\nORDER BY p.nextdate;\n\n-- Find the problem: active PM on decommissioned asset\nSELECT p.pmnum, p.assetnum, a.status AS asset_status\nFROM mx_pm p\nJOIN mx_asset a ON p.assetnum = a.assetnum\nWHERE p.status = 'ACTIVE' AND a.status = 'DECOMMISSIONED';",
                "sql_or_config": "-- Step 1: Deactivate PM for decommissioned asset\nUPDATE mx_pm SET status = 'INACTIVE'\nWHERE pmnum = 'PM-1003'\n  AND assetnum = 'FL-1003';\n\n-- Step 2: Verify no other PMs reference bad assets\nSELECT p.pmnum, p.assetnum, a.status\nFROM mx_pm p\nJOIN mx_asset a ON p.assetnum = a.assetnum\nWHERE p.status = 'ACTIVE'\n  AND a.status IN ('DECOMMISSIONED', 'BROKEN');\n\n-- Step 3: Restart cron task (in Maximo UI)\n-- Cron Task Setup > PMWOGEN > Instance > Reload Request\n\n-- Step 4: Force regeneration for missed PMs\n-- Run PMWOGen manually via Cron Task Setup\n\n-- Step 5: Verify new work orders were created\nSELECT wonum, description, pmnum, status, reportdate\nFROM mx_workorder\nWHERE pmnum IS NOT NULL\n  AND reportdate >= CURRENT_DATE\nORDER BY reportdate DESC;",
                "why_correct": "The PMWOGen cron task processes ALL active PMs in a single batch. When it hits a data integrity error (active PM pointing to a decommissioned asset), the entire batch fails. This is a known Maximo behavior — the cron task does not have per-record error handling. The fix addresses both the immediate problem (deactivate the bad PM) and validates all other PMs to prevent recurrence.",
                "what_to_document": "1. Incident ticket: INC-2026-0147 — PMWOGen failure affecting 47 PMs\n2. Root cause: PM-1003 referenced decommissioned asset FL-1003\n3. Fix: Deactivated PM-1003, restarted cron task, verified WO generation\n4. Prevention: Add validation script to run before PMWOGen — check for active PMs on decommissioned assets\n5. Change Request: CR-2026-0089 — Add asset status validation to PM activation workflow",
                "what_to_test": "1. Verify PMWOGEN cron task ran successfully after restart\n2. Confirm 47 overdue work orders were generated with correct dates\n3. Verify no PMs remain linked to decommissioned assets\n4. Check work order details match PM job plans\n5. Monitor next scheduled PMWOGen run (tonight) for success",
                "mentor_explanation": "This is a classic Maximo issue. The PMWOGen cron task is the heart of preventive maintenance — if it stops, maintenance doesn't happen, which creates safety and compliance risk. The key diagnostic skill is understanding that Maximo cron tasks process records in batches, and a single bad record can crash the entire batch. Always check the Maximo system log first (Start Center > System Log), then query the PM and asset tables to find data integrity mismatches. The permanent fix is adding a validation step — never just fix the one bad record without checking for others.",
                "interview_answer": "STAR: Situation — 47 preventive maintenance work orders failed to generate overnight for Water Utility fleet and pump equipment, creating compliance and safety risk. Task — Diagnose the PMWOGen cron task failure and restore PM generation before the next maintenance window. Action — Queried the Maximo PM and asset tables and found that one active PM (PM-1003) referenced a decommissioned asset, causing a duplicate key error (BMXAA4211E) that crashed the entire PMWOGen batch. Deactivated the orphaned PM, validated all remaining PM-to-asset relationships, restarted the cron task, and verified all 47 overdue work orders were generated. Result — PM generation restored within 2 hours. Created a change request to add asset status validation to the PM activation workflow, preventing this class of failure permanently. Documented the incident and added a monitoring alert for PMWOGen failures.",
                "skills_practiced": "sql_server,stored_procedures,debugging,change_mgmt,process_docs",
                "phase": "investigation",
            },
        ],
    },

    "maximo_duplicate_key": {
        "name": "M2: Maximo Duplicate Key Error on WOACTIVITY",
        "system": "maximo",
        "description": "Intermittent SQL Server error 2601 during work order creation affecting Parks Department.",
        "phases": ["investigation", "resolution"],
        "tasks": [
            {
                "title": "M2: Resolve WOACTIVITY Duplicate Key Error",
                "domain": "qa_debugging",
                "business_context": "Parks Department users report intermittent errors when creating work orders. Error: 'Cannot insert duplicate key row in object WOACTIVITY with unique index.' Happens approximately 1 in 10 attempts.",
                "description": "Investigate the duplicate key error, identify the root cause in the WOACTIVITY sequence, and resolve.",
                "evidence_reviewed": "SQL Server error log shows: 'Violation of UNIQUE KEY constraint UNQ_WOACTIVITY. Cannot insert duplicate key row in object dbo.WOACTIVITY. The duplicate key value is (WO-100025, 10, CCTX).' Database statistics on WOACTIVITY table were last updated 45 days ago. The WOSEQUENCE column uses a MAX+1 pattern that can race under concurrent access.",
                "decision_made": "Root cause: outdated database statistics combined with a sequence generation race condition. When two users create work orders simultaneously, the MAX(wosequence)+1 approach can generate the same sequence number.",
                "technical_detail": "-- Check for duplicate WOACTIVITY sequences\nSELECT parent, wosequence, COUNT(*) AS cnt\nFROM mx_workorder\nWHERE parent IS NOT NULL\nGROUP BY parent, wosequence\nHAVING COUNT(*) > 1;\n\n-- Check when statistics were last updated\nSELECT name, STATS_DATE(object_id, stats_id) AS stats_updated\nFROM sys.stats\nWHERE object_id = OBJECT_ID('mx_workorder');\n\n-- Performance impact: slow query before fix\n-- Time: 9,875ms\nSELECT * FROM mx_workorder\nWHERE parent = 'WO-100025' AND siteid = 'CCTX'\nORDER BY wosequence;",
                "sql_or_config": "-- Step 1: Update database statistics\nUPDATE STATISTICS mx_workorder WITH FULLSCAN;\nUPDATE STATISTICS mx_workorder WITH FULLSCAN;\nGO\n\n-- Step 2: Rebuild indexes on WOACTIVITY-related columns\nALTER INDEX ALL ON mx_workorder REBUILD;\nGO\n\n-- Step 3: Verify query performance improved\n-- Before: 9,875ms → After: 23ms\nSELECT * FROM mx_workorder\nWHERE parent = 'WO-100025' AND siteid = 'CCTX'\nORDER BY wosequence;\n\n-- Step 4: In Maximo, run Database Configuration > Update Statistics\n-- This ensures Maximo-level statistics are also current",
                "why_correct": "SQL Server uses statistics to generate query execution plans. Outdated statistics cause the optimizer to choose poor plans, which can lead to table scans instead of index seeks. This slows down the MAX+1 sequence generation query, widening the race condition window. Updating statistics and rebuilding indexes addresses both the performance issue and reduces the probability of sequence conflicts.",
                "what_to_document": "1. Incident: INC-2026-0152 — Intermittent duplicate key errors on work order creation\n2. Root cause: Outdated database statistics (45 days) + sequence race condition\n3. Fix: Updated statistics with FULLSCAN, rebuilt indexes\n4. Performance improvement: 9,875ms → 23ms on WOACTIVITY queries\n5. Prevention: Schedule weekly UPDATE STATISTICS job via SQL Server Agent",
                "what_to_test": "1. Have 3 Parks users create work orders simultaneously\n2. Verify no duplicate key errors occur\n3. Check query execution plan shows index seek (not scan)\n4. Monitor SQL Server error log for 24 hours for recurrence",
                "mentor_explanation": "Database statistics are one of the most overlooked aspects of enterprise application support. SQL Server's query optimizer depends entirely on statistics to decide how to execute queries. When statistics are stale, the optimizer makes bad choices — using table scans instead of index seeks, which can slow queries by 100x or more. In Maximo specifically, the Database Configuration application has a built-in 'Update Statistics' function that should be run regularly. Many Maximo administrators set up a weekly SQL Server Agent job to handle this automatically. The lesson: when you see intermittent performance issues, always check statistics freshness first.",
                "interview_answer": "STAR: Situation — Parks Department users experienced intermittent duplicate key errors when creating work orders in Maximo, failing roughly 1 in 10 attempts. Task — Diagnose the root cause and eliminate the errors. Action — Analyzed the SQL Server error log and found the duplicate key constraint violation on WOACTIVITY. Discovered database statistics hadn't been updated in 45 days, causing the query optimizer to use inefficient execution plans. This widened a race condition window in the sequence generation logic. Updated statistics with FULLSCAN and rebuilt indexes, reducing query time from 9,875ms to 23ms. Result — Zero duplicate key errors in the following week. Established a weekly automated statistics update job via SQL Server Agent to prevent recurrence.",
                "skills_practiced": "sql_server,debugging,iis_apache,process_docs",
                "phase": "investigation",
            },
        ],
    },

    "maximo_finance_integration": {
        "name": "M3: Maximo-to-Finance GL Integration Failure",
        "system": "maximo",
        "description": "SOAP interface to the city financial system returns BMXAA4211E errors. GL postings 3 days behind.",
        "phases": ["detection", "diagnosis", "resolution"],
        "tasks": [
            {
                "title": "M3: Restore Maximo GL Interface to Finance System",
                "domain": "app_integration",
                "business_context": "The city's finance department reports that General Ledger (GL) postings from Maximo work order costs have not appeared for 3 days. This affects the monthly close process and budget reporting accuracy. The integration uses SOAP web services through Maximo's Integration Framework.",
                "description": "Investigate the Integration Framework message queue, identify the communication failure, restore the GL interface.",
                "evidence_reviewed": "Maximo Integration > Message Tracking shows 47 messages in ERROR status for external system 'ABORFINANCE'. Error: 'BMXAA4211E - Connection refused: Finance GL endpoint unreachable.' The finance system's SOAP endpoint URL was changed during a weekend maintenance window but the Maximo endpoint configuration was not updated. Network team confirms the old URL is no longer valid.",
                "decision_made": "The finance system's SOAP endpoint URL changed during a maintenance window. The Maximo Integration Framework endpoint definition still points to the old URL. Need to update the endpoint, reprocess failed messages, and verify GL postings.",
                "technical_detail": "-- Check integration message errors\nSELECT msgid, extsysname, ifacename, status, msgerror,\n       createdate\nFROM mx_maxintmsgtrk\nWHERE extsysname = 'ABORFINANCE'\n  AND status = 'ERROR'\nORDER BY createdate DESC;\n\n-- Count messages by status\nSELECT status, COUNT(*) AS msg_count\nFROM mx_maxintmsgtrk\nWHERE extsysname = 'ABORFINANCE'\nGROUP BY status;\n\n-- In Maximo: Integration > End Points > ABORFINANCE\n-- Current URL: https://finance-old.cctx.gov/gl/soap\n-- New URL:     https://finance.cctx.gov/api/gl/soap",
                "sql_or_config": "-- Step 1: Update endpoint URL in Maximo\n-- Integration > End Points > ABORFINANCE\n-- Change URL from: https://finance-old.cctx.gov/gl/soap\n-- Change URL to:   https://finance.cctx.gov/api/gl/soap\n\n-- Step 2: Test connection\n-- Integration > External Systems > ABORFINANCE > Test Connection\n\n-- Step 3: Reprocess failed messages\n-- Integration > Message Reprocessing\n-- Filter: External System = ABORFINANCE, Status = ERROR\n-- Select All > Reprocess\n\n-- Step 4: Verify messages processed\nSELECT status, COUNT(*) AS msg_count\nFROM mx_maxintmsgtrk\nWHERE extsysname = 'ABORFINANCE'\n  AND createdate >= DATEADD(DAY, -3, GETDATE())\nGROUP BY status;\n\n-- Step 5: Confirm GL postings in finance system\n-- Finance team verifies 47 GL entries now posted",
                "why_correct": "Integration failures between enterprise systems are almost always caused by one of three things: endpoint URL changes, certificate expirations, or credential rotations. The diagnostic approach is: check the error message first (Connection refused = network/URL issue), then verify the endpoint configuration, then test connectivity. The Maximo Integration Framework stores endpoint definitions in a configuration table — changing the URL is a config change, not a code change. The critical follow-up is establishing a change notification process between the finance team and IT so endpoint changes are communicated before they happen.",
                "what_to_document": "1. Incident: INC-2026-0155 — GL Interface down for 3 days, 47 failed messages\n2. Root cause: Finance system endpoint URL changed during weekend maintenance without notification to Maximo team\n3. Fix: Updated endpoint URL, reprocessed 47 failed messages, verified GL postings\n4. Prevention: Establish change notification process between Finance IT and Applications team\n5. Change Request: CR-2026-0091 — Add integration health monitoring with automated alerts",
                "what_to_test": "1. Verify all 47 reprocessed messages show PROCESSED status\n2. Finance team confirms GL entries for the 3-day gap\n3. Create a new work order with costs and verify GL posting flows within 15 minutes\n4. Monitor integration queue for 24 hours\n5. Verify automated alert fires if error count exceeds threshold",
                "mentor_explanation": "Integration monitoring is one of the most critical responsibilities for an enterprise applications analyst. When integrations fail silently, the business impact compounds daily. The lesson here is three-fold: (1) Always have monitoring on integration queues — don't wait for users to report missing data. (2) Establish change notification processes between teams — this failure was 100% preventable if the finance team had notified the Maximo team of the URL change. (3) Know how to use the Maximo Message Reprocessing tool — it can recover from most transient failures without data loss.",
                "interview_answer": "STAR: Situation — The Maximo-to-Finance GL integration had been down for 3 days, with 47 failed messages preventing work order costs from posting to the General Ledger. This impacted the monthly financial close. Task — Diagnose the integration failure, restore the interface, and recover the 3-day data gap. Action — Examined the Maximo Integration Framework message queue and found 'Connection refused' errors pointing to an endpoint URL change. The finance system had migrated to a new URL during weekend maintenance without notifying our team. Updated the endpoint configuration, tested connectivity, and used Maximo's Message Reprocessing tool to recover all 47 failed messages. Result — All GL postings recovered within 2 hours. Established a formal change notification process between Finance IT and Applications, and implemented automated integration health monitoring with alerts when error counts exceed thresholds.",
                "skills_practiced": "web_services,debugging,sql_server,change_mgmt,process_docs",
                "phase": "detection",
            },
        ],
    },

    # ================================================================
    #  TYLER INCODE SCENARIOS (T1-T4)
    # ================================================================

    "incode_citation_import": {
        "name": "T1: Tyler Incode Citation Import Failure",
        "system": "incode",
        "description": "Nightly citation feed from PD failed. 142 citations not imported. XML parsing error at line 89.",
        "phases": ["investigation", "resolution"],
        "tasks": [
            {
                "title": "T1: Fix Citation Import XML Parsing Failure",
                "domain": "app_integration",
                "business_context": "The nightly citation import from CCPD's Records Management System (RMS) failed. 142 citations from yesterday's traffic enforcement are stuck in the import queue. Court clerks cannot process arraignments for these citations until they are imported into Incode.",
                "description": "Investigate the XML parsing error, identify the schema mismatch, fix the import mapping, and reprocess failed citations.",
                "evidence_reviewed": "Import log shows: 'XML Parse Error: Unexpected element VehicleMake2 at line 89.' The PD's RMS system was updated last week with a new field 'VehicleMake2' for secondary vehicle descriptions (e.g., trailers). Our Incode import mapping does not expect this field. The XSD schema file on our import server is version 3.1; PD's export is now version 3.2.",
                "decision_made": "The PD system added a new XML element that our import parser doesn't recognize. Need to update the XSD schema and import mapping to either accept or ignore the new field, then reprocess the failed batch.",
                "technical_detail": "-- Check failed citation imports\nSELECT citation_number, violation_desc, import_status,\n       import_error, import_batch\nFROM ic_citation\nWHERE import_status = 'ERROR'\nORDER BY created_at DESC;\n\n-- Sample of the XML that fails:\n-- <Citation>\n--   <CitationNumber>CIT-2026-10115</CitationNumber>\n--   <VehicleMake>Ford</VehicleMake>\n--   <VehicleMake2>Trailer-Utility</VehicleMake2>  ← NEW FIELD\n--   <VehiclePlate>ABC-1234</VehiclePlate>\n-- </Citation>\n\n-- Our XSD expects:\n-- <xs:element name=\"VehicleMake\" type=\"xs:string\"/>\n-- Missing: VehicleMake2 definition",
                "sql_or_config": "-- Step 1: Update the XSD schema file\n-- Add to citation_import.xsd:\n-- <xs:element name=\"VehicleMake2\" type=\"xs:string\" minOccurs=\"0\"/>\n\n-- Step 2: Update import mapping (if field should be stored)\n-- Incode Admin > Import Configuration > Citation Fields\n-- Add mapping: XML:VehicleMake2 → DB:vehicle_make_secondary\n-- OR set to IGNORE if field is not needed\n\n-- Step 3: Reprocess failed batch\n-- Incode Admin > Import Queue > Select Batch BATCH-20260224\n-- Click 'Reprocess'\n\n-- Step 4: Verify import success\nSELECT import_status, COUNT(*) AS cnt\nFROM ic_citation\nWHERE import_batch = 'BATCH-20260224'\nGROUP BY import_status;\n\n-- Step 5: Verify all 142 citations now available for clerks\nSELECT COUNT(*) AS imported\nFROM ic_citation\nWHERE import_batch = 'BATCH-20260224'\n  AND import_status = 'IMPORTED';",
                "why_correct": "XML schema mismatches are the most common cause of integration import failures. When an upstream system adds a new field, our parser rejects the entire document if it uses strict schema validation. The fix is to update the XSD to accept the new element (with minOccurs=0 so it's optional), then decide whether to map it to a database field or ignore it. The critical lesson: always ask the upstream team for release notes before they deploy updates.",
                "what_to_document": "1. Incident: INC-2026-0148 — 142 citations failed import due to XML schema mismatch\n2. Root cause: PD RMS system v3.2 added VehicleMake2 element not in our XSD v3.1\n3. Fix: Updated XSD schema, reprocessed batch, all 142 citations imported\n4. Prevention: Establish pre-deployment notification from PD IT for RMS updates\n5. Updated import mapping documentation with new field",
                "what_to_test": "1. Verify all 142 citations show IMPORTED status\n2. Spot-check 5 citations in Incode case management for correct data\n3. Process a new test citation with VehicleMake2 field present\n4. Process a test citation WITHOUT VehicleMake2 (backward compatibility)\n5. Monitor tonight's automated import for success",
                "mentor_explanation": "Citation imports are the lifeblood of a municipal court. If citations don't import, cases can't be created, defendants can't be notified, and court dates can't be set. When you see an XML parsing error, the diagnostic steps are: (1) Get the exact error line and element name. (2) Compare the incoming XML against your expected schema (XSD). (3) Identify what changed. (4) Decide: accept the new field or ignore it? (5) Update the schema and mapping. (6) Reprocess. The permanent fix is establishing communication channels with upstream teams so you get advance notice of schema changes.",
                "interview_answer": "STAR: Situation — 142 traffic citations failed to import overnight from the police department's RMS system, blocking court clerks from processing arraignments. Task — Diagnose the import failure, fix it, and restore the citation pipeline before morning court sessions. Action — Examined the import log and found an XML parsing error caused by a new 'VehicleMake2' field added in the PD's latest RMS update. Our XSD schema was version 3.1 and didn't recognize the new element. Updated the schema to accept the optional field, reprocessed the failed batch, and verified all 142 citations imported correctly. Result — All citations available for court processing within 90 minutes of diagnosis. Established a formal change notification process with PD IT for future RMS updates.",
                "skills_practiced": "web_services,debugging,sql_server,process_docs,change_mgmt",
                "phase": "investigation",
            },
        ],
    },

    "incode_payment_mismatch": {
        "name": "T2: Tyler Incode Payment Posting Mismatch",
        "system": "incode",
        "description": "Online payment gateway posted $4,230 but Incode shows $3,890. $340 variance needs investigation.",
        "phases": ["investigation", "reconciliation"],
        "tasks": [
            {
                "title": "T2: Reconcile Payment Gateway vs. Incode Variance",
                "domain": "sql_reporting",
                "business_context": "The court cashier's daily reconciliation shows the online payment gateway processed $4,230 in payments yesterday, but the Incode payment ledger shows only $3,890 posted. The $340 variance must be identified and resolved before the bank deposit can be finalized.",
                "description": "Compare gateway transactions against Incode payment records, identify the unposted payments, determine why they failed to post, and reconcile.",
                "evidence_reviewed": "Gateway settlement report: 23 transactions totaling $4,230.00. Incode payment table: 21 posted transactions totaling $3,890.00. Two transactions ($195.00 + $145.00 = $340.00) show posted = FALSE. Both have gateway_txn_id values that exist in the gateway report. Both payments were for cases in WARRANT status.",
                "decision_made": "Two online payments failed to post to Incode because the cases were in WARRANT status at the time of payment. Incode's payment posting routine has a business rule that rejects payments on WARRANT cases that haven't been recalled by the court. Need to recall the warrants, post the payments, and review the business rule.",
                "technical_detail": "-- Step 1: Find unposted payments with gateway transactions\nSELECT p.payment_id, p.case_number, p.amount,\n       p.gateway_txn_id, p.posted, p.payment_date,\n       c.status AS case_status, c.warrant_number\nFROM ic_payment p\nJOIN ic_case c ON p.case_number = c.case_number\nWHERE p.posted = FALSE\n  AND p.gateway_txn_id IS NOT NULL\nORDER BY p.payment_date DESC;\n\n-- Step 2: Verify the dollar amounts match the gap\nSELECT SUM(amount) AS unposted_total\nFROM ic_payment\nWHERE posted = FALSE AND gateway_txn_id IS NOT NULL;\n-- Result: $340.00 ✓ matches the variance\n\n-- Step 3: Check the warrant status for these cases\nSELECT w.warrant_number, w.case_number, w.status,\n       w.issue_date, c.defendant_id\nFROM ic_warrant w\nJOIN ic_case c ON w.case_number = c.case_number\nWHERE c.case_number IN (\n    SELECT case_number FROM ic_payment\n    WHERE posted = FALSE AND gateway_txn_id IS NOT NULL\n);",
                "sql_or_config": "-- Step 1: Recall the warrants (defendant paid, so warrant should be cleared)\nUPDATE ic_warrant\nSET status = 'RECALLED', recalled_date = CURRENT_DATE\nWHERE case_number IN (\n    SELECT case_number FROM ic_payment\n    WHERE posted = FALSE AND gateway_txn_id IS NOT NULL\n);\n\n-- Step 2: Update case status from WARRANT to OPEN\nUPDATE ic_case\nSET status = 'OPEN', warrant_issued = FALSE\nWHERE case_number IN (\n    SELECT case_number FROM ic_payment\n    WHERE posted = FALSE AND gateway_txn_id IS NOT NULL\n);\n\n-- Step 3: Post the payments\nUPDATE ic_payment\nSET posted = TRUE, posted_date = CURRENT_TIMESTAMP\nWHERE posted = FALSE AND gateway_txn_id IS NOT NULL;\n\n-- Step 4: Update case balances\nUPDATE ic_case c\nSET total_paid = (\n    SELECT COALESCE(SUM(p.amount), 0)\n    FROM ic_payment p\n    WHERE p.case_number = c.case_number AND p.posted = TRUE\n),\nbalance_due = total_due - (\n    SELECT COALESCE(SUM(p.amount), 0)\n    FROM ic_payment p\n    WHERE p.case_number = c.case_number AND p.posted = TRUE\n)\nWHERE c.case_number IN (\n    SELECT case_number FROM ic_payment\n    WHERE posted_date >= CURRENT_DATE\n);\n\n-- Step 5: Verify reconciliation\nSELECT SUM(amount) AS total_posted\nFROM ic_payment\nWHERE posted = TRUE\n  AND payment_date >= CURRENT_DATE - INTERVAL '1 day';\n-- Should now equal $4,230.00",
                "why_correct": "Payment reconciliation is a critical financial control. The methodology is: (1) Get the authoritative total from the payment gateway. (2) Compare against the court system total. (3) Identify specific unmatched transactions. (4) Determine WHY they didn't post (business rule, error, timing). (5) Apply the appropriate fix (don't just force-post without understanding the rule). (6) Verify the totals match. In this case, the warrant-status business rule is correct in general (courts should review warrant payments), but the online payment portal should handle this case gracefully rather than silently failing.",
                "what_to_document": "1. Reconciliation report: Gateway $4,230 vs Incode $3,890, variance $340\n2. Root cause: 2 payments on WARRANT-status cases rejected by posting routine\n3. Fix: Recalled warrants, posted payments, updated balances\n4. Recommendation: Modify online payment portal to show warning for warrant cases or auto-trigger warrant recall workflow\n5. Daily reconciliation checklist updated with warrant payment check step",
                "what_to_test": "1. Verify total posted payments now equal $4,230\n2. Verify both case balances updated correctly\n3. Verify warrants show RECALLED status\n4. Run the daily reconciliation report — confirm zero variance\n5. Process a test online payment for a warrant case to verify the fix",
                "mentor_explanation": "Payment reconciliation is the skill that makes or breaks a court applications analyst. When money is involved, precision matters — every penny must be accounted for. The approach is always the same: get both numbers, find the delta, identify the specific transactions causing the gap, understand WHY they're different, fix it, and PROVE the fix with a reconciliation report. Never just adjust numbers to make them match — always find and fix the root cause. In interviews, this scenario demonstrates your financial system knowledge, SQL skills, and attention to detail.",
                "interview_answer": "STAR: Situation — Daily payment reconciliation showed a $340 variance between the online payment gateway ($4,230) and the court's Incode system ($3,890). Task — Identify the unmatched transactions, determine why they failed to post, reconcile, and prevent recurrence. Action — Wrote SQL queries to compare gateway transaction IDs against Incode payment records. Found two unposted payments totaling $340, both for cases in WARRANT status. The posting routine's business rule rejected payments on warrant cases. Recalled the warrants (since defendants had paid), posted the payments, and updated case balances. Verified the reconciliation showed zero variance. Result — Reconciliation completed within 1 hour. Recommended modifying the online payment portal to handle warrant-status payments gracefully, which was implemented in the next sprint.",
                "skills_practiced": "sql_server,crystal_reports,debugging,process_docs",
                "phase": "investigation",
            },
        ],
    },

    "incode_docket_error": {
        "name": "T3: Tyler Incode Docket Generation Error",
        "system": "incode",
        "description": "Monthly docket for Courtroom B producing blank pages. Crystal Report stored procedure returning NULL for judge assignment.",
        "phases": ["investigation", "resolution"],
        "tasks": [
            {
                "title": "T3: Fix Courtroom B Docket Report — NULL Judge Assignment",
                "domain": "sql_reporting",
                "business_context": "Court Clerk reports the Courtroom B docket for next week generates blank pages. Courtrooms A and C dockets work correctly. The docket is a Crystal Report that pulls case data for each courtroom and judge.",
                "description": "Investigate why the Courtroom B docket Crystal Report produces blank output, identify the data issue, fix it.",
                "evidence_reviewed": "Crystal Report data source is stored procedure sp_GenerateDocket. Running it for Courtroom B returns 0 rows. Running it for Courtroom A returns 35 rows. Checking the ic_docket table shows Courtroom B's docket entry has judge_id = NULL. The judge was reassigned last week and the docket record was not updated.",
                "decision_made": "The docket record for Courtroom B has a NULL judge_id because the judge reassignment was not propagated to the docket table. The Crystal Report's stored procedure uses an INNER JOIN on judge_id, which drops all rows when judge_id is NULL.",
                "technical_detail": "-- Reproduce: run the stored procedure\n-- For Courtroom A (works):\nEXEC sp_GenerateDocket @Courtroom = 'A', @DocketDate = '2026-03-04';\n-- Returns 35 rows ✓\n\n-- For Courtroom B (fails):\nEXEC sp_GenerateDocket @Courtroom = 'B', @DocketDate = '2026-03-11';\n-- Returns 0 rows ✗\n\n-- Check docket records\nSELECT docket_id, docket_date, courtroom, judge_id, judge_name,\n       case_count, status\nFROM ic_docket\nWHERE docket_date >= CURRENT_DATE\nORDER BY docket_date;\n\n-- Found: Courtroom B has judge_id = NULL, judge_name = NULL\n\n-- The stored procedure uses INNER JOIN:\n-- FROM ic_case c\n-- INNER JOIN ic_docket d ON c.courtroom = d.courtroom\n--   AND c.judge_id = d.judge_id  ← NULL never matches!",
                "sql_or_config": "-- Step 1: Update the docket with the new judge\nUPDATE ic_docket\nSET judge_id = 'JDG-002',\n    judge_name = 'Judge Mitchell'\nWHERE courtroom = 'B'\n  AND docket_date = '2026-03-11';\n\n-- Step 2: Update cases assigned to Courtroom B\nUPDATE ic_case\nSET judge_id = 'JDG-002',\n    judge_name = 'Judge Mitchell'\nWHERE courtroom = 'B'\n  AND court_date = '2026-03-11'\n  AND judge_id IS NULL;\n\n-- Step 3: Fix the stored procedure to handle NULL gracefully\n-- ALTER the JOIN to use courtroom only (not judge_id)\n-- OR add COALESCE: AND c.judge_id = COALESCE(d.judge_id, c.judge_id)\n\n-- Step 4: Regenerate the docket\nEXEC sp_GenerateDocket @Courtroom = 'B', @DocketDate = '2026-03-11';\n-- Now returns 28 rows ✓\n\n-- Step 5: Verify in Crystal Reports\n-- Preview Courtroom B docket — 28 cases displayed correctly",
                "why_correct": "This is a classic reporting bug: an INNER JOIN that silently drops rows when a key column is NULL. NULL never equals NULL in SQL, so INNER JOIN on a NULL column returns zero rows. The fix has two parts: (1) fix the immediate data issue (assign the judge), and (2) fix the stored procedure so it handles NULL gracefully (use LEFT JOIN or COALESCE). The second fix prevents this from happening again when the next judge reassignment occurs.",
                "what_to_document": "1. Incident: INC-2026-0160 — Courtroom B docket blank due to NULL judge assignment\n2. Root cause: Judge reassignment not propagated to docket table; INNER JOIN on NULL returns 0 rows\n3. Immediate fix: Updated docket and case records with new judge\n4. Permanent fix: Modified stored procedure to handle NULL judge_id\n5. Process improvement: Add judge reassignment to docket update checklist",
                "what_to_test": "1. Preview Courtroom B docket in Crystal Reports — verify 28 cases show\n2. Preview Courtrooms A and C — verify no regression\n3. Test with a deliberately NULL judge_id to confirm the SP fix works\n4. Print a test copy for the Court Clerk to verify formatting",
                "mentor_explanation": "NULL handling in SQL is responsible for more reporting bugs than any other single issue. Remember: NULL is not a value — it's the absence of a value. NULL = NULL evaluates to FALSE, not TRUE. This means INNER JOINs silently drop rows with NULL keys, aggregate functions ignore NULLs, and WHERE column = NULL never matches (you must use WHERE column IS NULL). When a report produces fewer rows than expected, always check for NULL key columns first. In Crystal Reports specifically, the data source is usually a stored procedure — so debugging starts in SQL, not in the report designer.",
                "interview_answer": "STAR: Situation — Court clerk reported the Courtroom B docket was generating blank pages, while Courtrooms A and C worked correctly. Task — Diagnose and fix the issue before the next scheduled court date. Action — Traced the Crystal Report to its stored procedure data source. Running it for Courtroom B returned 0 rows. Discovered the docket record had NULL for judge_id after a reassignment wasn't propagated. The stored procedure's INNER JOIN on judge_id dropped all rows because NULL never equals NULL. Updated the docket data with the correct judge and modified the stored procedure to use COALESCE, preventing future NULL-related failures. Result — Docket generated correctly with 28 cases. Added judge reassignment to the docket update checklist to prevent recurrence.",
                "skills_practiced": "sql_server,stored_procedures,crystal_reports,debugging,process_docs",
                "phase": "investigation",
            },
        ],
    },

    "incode_warrant_interface": {
        "name": "T4: Tyler Incode Warrant Interface Failure — TCIC/NCIC",
        "system": "incode",
        "description": "TCIC/NCIC warrant upload returning authentication error after state system certificate rotation.",
        "phases": ["detection", "resolution"],
        "tasks": [
            {
                "title": "T4: Restore TCIC/NCIC Warrant Upload — Certificate Expired",
                "domain": "app_integration",
                "business_context": "The automated warrant upload to TCIC (Texas Crime Information Center) and NCIC (National Crime Information Center) failed overnight. 15 new warrants are not in the state system, meaning officers cannot verify them during traffic stops. This is a public safety issue.",
                "description": "Diagnose the warrant interface authentication failure, replace the expired certificate, and reprocess failed warrant uploads.",
                "evidence_reviewed": "Warrant upload log: 'SSL Handshake Error: Certificate CN=CCTX-Warrant-Upload expired 2026-02-24.' The client certificate used for mutual TLS with the DPS (Department of Public Safety) gateway expired yesterday. Last certificate renewal was 2 years ago. No automated renewal process exists.",
                "decision_made": "The client SSL certificate for the TCIC/NCIC warrant interface expired. Need to generate a new CSR, get it signed by DPS, install the new cert, and reprocess the failed uploads.",
                "technical_detail": "-- Check warrant upload errors\nSELECT warrant_number, case_number, status,\n       tcic_status, upload_error, last_upload\nFROM ic_warrant\nWHERE status = 'ACTIVE'\n  AND (tcic_status = 'ERROR' OR tcic_status IS NULL)\nORDER BY issue_date DESC;\n\n-- Certificate check (PowerShell):\n-- Get-ChildItem Cert:\\LocalMachine\\My |\n--   Where-Object {$_.Subject -like '*Warrant*'} |\n--   Select-Object Subject, NotAfter, Thumbprint\n--\n-- Subject: CN=CCTX-Warrant-Upload\n-- NotAfter: 2/24/2026 ← EXPIRED\n-- Thumbprint: A1B2C3D4...",
                "sql_or_config": "# PowerShell: Generate new certificate\n$cert = New-SelfSignedCertificate `\n    -Subject 'CN=CCTX-Warrant-Upload' `\n    -KeyAlgorithm RSA -KeyLength 2048 `\n    -NotAfter (Get-Date).AddYears(2) `\n    -CertStoreLocation 'Cert:\\LocalMachine\\My' `\n    -KeyUsage DigitalSignature, KeyEncipherment `\n    -TextExtension @('2.5.29.37={text}1.3.6.1.5.5.7.3.2')\n\n# Export CSR for DPS signing\n$csr = certreq -new warrant_cert.inf warrant_csr.req\n\n# After DPS signs and returns the cert:\n# Import signed certificate\ncertreq -accept dps_signed_cert.cer\n\n# Update Incode warrant upload configuration\n# Admin > Interfaces > TCIC/NCIC > Certificate\n# Select new certificate thumbprint\n\n# Test connection\nInvoke-WebRequest -Uri 'https://tcic-gateway.dps.texas.gov/test' `\n    -Certificate $cert -Method POST\n\n# Reprocess failed warrants\n# Admin > Warrant Upload > Reprocess Failed",
                "why_correct": "Certificate management is critical for law enforcement interfaces. TCIC/NCIC require mutual TLS (mTLS) where both the server and client present certificates. When our client cert expires, the state gateway rejects our connection. The fix follows the standard certificate lifecycle: generate new key pair, create CSR, submit to the authority (DPS in this case), install the signed cert, update the application config, and test. The prevention is implementing certificate expiry monitoring — alert at 30, 14, and 7 days before expiration.",
                "what_to_document": "1. CRITICAL Incident: INC-2026-0149 — TCIC/NCIC warrant upload down, 15 warrants not in state system\n2. Root cause: Client SSL certificate expired 2026-02-24\n3. Fix: Generated new cert, submitted CSR to DPS, installed signed cert, reprocessed uploads\n4. Prevention: Implemented certificate expiry monitoring script (30/14/7 day alerts)\n5. Updated runbook: Warrant Interface Certificate Renewal Procedure",
                "what_to_test": "1. Upload a test warrant to TCIC staging environment\n2. Verify successful SSL handshake in logs\n3. Reprocess all 15 failed warrant uploads\n4. Confirm TCIC status = 'UPLOADED' for all active warrants\n5. DPS confirms receipt of warrant records\n6. Set calendar reminder for next cert renewal (2028-02-24)",
                "mentor_explanation": "Warrant interfaces are among the most critical integrations in municipal IT — they directly affect public safety. Officers in the field rely on TCIC/NCIC to verify warrants during traffic stops. If warrants aren't uploaded, a person with an active warrant could be released. This is why this incident is classified as CRITICAL, not just HIGH. The technical skill is certificate management (CSR generation, chain of trust, mTLS). The operational skill is implementing proactive monitoring so you never have to deal with expired certs as an emergency again.",
                "interview_answer": "STAR: Situation — The TCIC/NCIC warrant upload interface failed, leaving 15 active warrants not in the state system — a public safety issue for officers in the field. Task — Restore the warrant interface immediately and prevent recurrence. Action — Identified the root cause as an expired client SSL certificate for the mutual TLS connection to the DPS gateway. Generated a new certificate, submitted the CSR to DPS for signing, installed the signed cert, updated the Incode configuration, and reprocessed all 15 failed uploads. Result — Warrant interface restored within 4 hours (fastest possible given DPS cert signing turnaround). All 15 warrants verified in TCIC. Implemented a PowerShell monitoring script that alerts at 30, 14, and 7 days before certificate expiration, eliminating the risk of future surprise expirations.",
                "skills_practiced": "web_services,powershell,iis_apache,debugging,process_docs,change_mgmt",
                "phase": "detection",
            },
        ],
    },

    # ================================================================
    #  E-BUILDER SCENARIOS (E1-E3)
    # ================================================================

    "ebuilder_api_auth": {
        "name": "E1: e-Builder API Authentication Failure",
        "system": "ebuilder",
        "description": "e-Builder REST API returning 401 after API key rotation. CIP project data sync broken for 2 days.",
        "phases": ["investigation", "resolution"],
        "tasks": [
            {
                "title": "E1: Restore e-Builder API Connection After Key Rotation",
                "domain": "app_integration",
                "business_context": "The automated sync between e-Builder and the city's financial system has been down for 2 days. CIP project managers cannot see current cost data, and finance cannot reconcile project expenditures. The sync uses e-Builder's REST API with API key authentication.",
                "description": "Diagnose the API authentication failure, obtain a new API key, update the integration configuration, and verify data sync.",
                "evidence_reviewed": "Integration log shows HTTP 401 Unauthorized responses starting 2 days ago. The e-Builder admin console shows the API key was 'rotated' during a scheduled security maintenance. The old key was invalidated but the integration config still uses it. The API base URL is correct: https://api2.e-builder.net.",
                "decision_made": "The API key was rotated during security maintenance. Need to generate a new key in the e-Builder admin console, update the integration configuration, and re-sync the 2-day data gap.",
                "technical_detail": "-- Check integration logs for the error pattern\n-- Log entry: 2026-02-23 02:00:15 ERROR\n-- POST https://api2.e-builder.net/api/v2/costs\n-- Response: 401 Unauthorized\n-- Body: {\"error\": \"Invalid or expired API key\"}\n\n-- Verify the API endpoint is reachable\n-- curl -I https://api2.e-builder.net/health\n-- HTTP/2 200 OK  ← Server is up, auth is the problem\n\n-- Check current API key configuration\n-- Integration Config > e-Builder > API Settings\n-- Key: eb_api_****_old  ← This key was invalidated",
                "sql_or_config": "# Step 1: Generate new API key in e-Builder\n# Admin > Administration Tools > APIs > Access\n# Click 'Create Key' > Select API User > Download\n\n# Step 2: Test new key\ncurl -X GET 'https://api2.e-builder.net/api/v2/projects' \\\n  -H 'Authorization: Bearer NEW_API_KEY_HERE' \\\n  -H 'Content-Type: application/json'\n# Expected: 200 OK with project list\n\n# Step 3: Update integration configuration\n# Integration Config > e-Builder > API Settings\n# Replace API key with new value\n# Save and test connection\n\n# Step 4: Trigger manual sync for missed 2 days\n# Integration Admin > e-Builder Sync > Run Now\n# Date range: 2026-02-23 to 2026-02-25\n\n# Step 5: Verify costs synced\nSELECT project_id, COUNT(*) AS cost_items,\n       SUM(actual) AS total_synced\nFROM eb_cost_item\nWHERE invoice_date >= '2026-02-23'\nGROUP BY project_id;",
                "why_correct": "API key rotation is a standard security practice, but it breaks integrations if the key isn't updated in all consuming applications. The diagnostic approach: (1) Check the HTTP status code (401 = auth issue). (2) Verify the endpoint is reachable (separate network from auth). (3) Check when the key was last rotated. (4) Generate new key, test, deploy, sync. The prevention is coordinating security maintenance with integration teams.",
                "what_to_document": "1. Incident: INC-2026-0162 — e-Builder API sync down for 2 days\n2. Root cause: API key rotated during security maintenance without updating integration\n3. Fix: Generated new API key, updated config, synced 2-day data gap\n4. Prevention: Add integration team to security maintenance notification list\n5. Runbook updated: e-Builder API Key Rotation Procedure",
                "what_to_test": "1. Verify API returns 200 with new key\n2. Verify cost data for all 8 CIP projects synced correctly\n3. Compare e-Builder totals with finance system for the 2-day gap\n4. Verify automated nightly sync runs successfully\n5. Confirm project managers can see current cost data in e-Builder",
                "mentor_explanation": "API key management is an increasingly important skill as more municipal systems move to cloud and API-based integrations. The lesson: always have a runbook for key rotation that includes every consuming application. When a key is rotated, every integration that uses it must be updated. In larger organizations, this is managed through secrets management tools (like HashiCorp Vault or Azure Key Vault). For smaller municipalities, a documented checklist and notification process is the minimum.",
                "interview_answer": "STAR: Situation — The e-Builder CIP project management sync had been down for 2 days, preventing project managers from seeing current cost data and blocking finance reconciliation. Task — Diagnose the sync failure and restore data flow for 8 active CIP projects. Action — Identified HTTP 401 errors in the integration log caused by an API key rotation during security maintenance. Generated a new API key in the e-Builder admin console, tested it, updated the integration configuration, and ran a manual sync for the 2-day data gap. Verified all project cost data reconciled. Result — Sync restored within 1 hour. Added the integration team to the security maintenance notification process to prevent future surprises. Created a runbook for API key rotation that includes all consuming applications.",
                "skills_practiced": "web_services,debugging,process_docs,change_mgmt",
                "phase": "investigation",
            },
        ],
    },

    "ebuilder_cost_mismatch": {
        "name": "E2: e-Builder CIP Budget vs. Finance Variance",
        "system": "ebuilder",
        "description": "$2.3M CIP project shows $180K budget variance between e-Builder and finance system.",
        "phases": ["investigation", "reconciliation"],
        "tasks": [
            {
                "title": "E2: Investigate $180K CIP Budget Variance — Oso Creek Project",
                "domain": "sql_reporting",
                "business_context": "The Oso Creek Water Reclamation Facility Upgrade project ($45M budget) shows a $180K variance between e-Builder's cost tracking and the city's financial system. The City Manager's monthly CIP report is due Friday, and this variance must be explained.",
                "description": "Compare cost data between e-Builder and the finance system, identify the variance source, reconcile, and document for the City Manager's report.",
                "evidence_reviewed": "e-Builder project CIP-2024-001 shows $27.2M actual cost. Finance GL shows $27.02M for the same project fund code. Variance: $180K. Drilling into cost items, found 3 invoices in e-Builder marked 'actual' but not yet 'posted_to_finance' — they were approved in e-Builder but the cost sync failed during the API outage (E1).",
                "decision_made": "The $180K variance is caused by 3 invoices ($72K + $63K + $45K) that were recorded in e-Builder during the 2-day API outage but not synced to the finance system. The invoices are legitimate and need to be posted.",
                "technical_detail": "-- Step 1: Identify unposted cost items for CIP-2024-001\nSELECT cost_id, cost_code, description, category,\n       actual, vendor, invoice_number, invoice_date,\n       posted_to_finance\nFROM eb_cost_item\nWHERE project_id = 'CIP-2024-001'\n  AND posted_to_finance = FALSE\nORDER BY invoice_date;\n\n-- Step 2: Verify the unposted total matches the variance\nSELECT SUM(actual) AS unposted_total\nFROM eb_cost_item\nWHERE project_id = 'CIP-2024-001'\n  AND posted_to_finance = FALSE;\n-- Expected: ~$180,000\n\n-- Step 3: Compare totals\nSELECT \n    SUM(actual) AS ebuilder_total,\n    SUM(CASE WHEN posted_to_finance THEN actual ELSE 0 END) AS finance_total,\n    SUM(CASE WHEN NOT posted_to_finance THEN actual ELSE 0 END) AS variance\nFROM eb_cost_item\nWHERE project_id = 'CIP-2024-001';",
                "sql_or_config": "-- Step 1: Post the 3 unsynced invoices to finance\nUPDATE eb_cost_item\nSET posted_to_finance = TRUE\nWHERE project_id = 'CIP-2024-001'\n  AND posted_to_finance = FALSE;\n\n-- Step 2: Trigger finance system sync\n-- Finance Admin > Manual Journal Entry\n-- Upload: CIP-2024-001 cost adjustment batch\n\n-- Step 3: Verify reconciliation\nSELECT \n    SUM(actual) AS ebuilder_total,\n    SUM(CASE WHEN posted_to_finance THEN actual ELSE 0 END) AS finance_total,\n    SUM(CASE WHEN NOT posted_to_finance THEN actual ELSE 0 END) AS remaining_variance\nFROM eb_cost_item\nWHERE project_id = 'CIP-2024-001';\n-- remaining_variance should be $0\n\n-- Step 4: Generate reconciliation report for City Manager\n-- Include: Project ID, Budget, e-Builder Actual, Finance Actual, Variance, Explanation",
                "why_correct": "CIP budget variances are high-visibility issues because they go directly to the City Manager and City Council. The approach is always: (1) Quantify the exact variance. (2) Identify specific transactions causing it. (3) Determine if it's a timing issue (data not synced yet) vs. a real discrepancy. (4) Fix the sync issue. (5) Produce a clear reconciliation report that a non-technical executive can understand.",
                "what_to_document": "1. Reconciliation memo for City Manager:\n   - Variance: $180K on CIP-2024-001 (Oso Creek)\n   - Cause: 3 invoices delayed by API sync outage\n   - Status: Resolved — all costs now posted\n   - Impact: No budget overrun — costs were legitimate approved expenditures\n2. Updated project cost report\n3. Link to incident INC-2026-0162 (API outage root cause)",
                "what_to_test": "1. Verify all cost items for CIP-2024-001 show posted_to_finance = TRUE\n2. Verify finance system GL matches e-Builder total for the project\n3. Run the CIP monthly status report — verify Oso Creek shows correct budget vs. actual\n4. Check all other projects for similar unposted items from the outage period",
                "mentor_explanation": "Budget reconciliation for CIP projects is one of the highest-stakes tasks in municipal IT. These projects are funded by voter-approved bonds, and every dollar must be accounted for. When you find a variance, the City Manager needs to know three things: How much? Why? Is it fixed? Keep your explanation simple and factual. In this case, the variance was caused by a temporary sync issue (which you already fixed in E1), and the money was legitimately spent — no fraud, no overrun, just a timing gap.",
                "interview_answer": "STAR: Situation — A $180K variance between e-Builder and the finance system on a $45M CIP project was flagged before the City Manager's monthly report. Task — Identify the root cause, reconcile the accounts, and provide a clear explanation for the executive report. Action — Queried e-Builder cost items and found 3 invoices totaling $180K that were approved but not synced to finance during a 2-day API outage. Verified the invoices were legitimate approved expenditures. Posted the items to finance, confirmed zero variance, and prepared a reconciliation memo explaining the timing issue. Result — Variance resolved and documented. City Manager's report included a clear one-paragraph explanation. No budget overrun — just a temporary data sync delay that was already fixed.",
                "skills_practiced": "sql_server,crystal_reports,debugging,process_docs",
                "phase": "investigation",
            },
        ],
    },

    "ebuilder_doc_sync": {
        "name": "E3: e-Builder Document Sync to SharePoint Failure",
        "system": "ebuilder",
        "description": "Construction submittals not syncing to SharePoint. 34 documents stuck in queue.",
        "phases": ["investigation", "resolution"],
        "tasks": [
            {
                "title": "E3: Restore e-Builder to SharePoint Document Sync",
                "domain": "app_integration",
                "business_context": "Construction submittals, drawings, and specs from e-Builder are not syncing to SharePoint where project teams access them. 34 documents are stuck with 'ERROR' sync status. Engineers and inspectors cannot access the latest construction documents in the field.",
                "description": "Diagnose the SharePoint sync failure, fix the connectivity issue, and reprocess stuck documents.",
                "evidence_reviewed": "e-Builder sync log: 'SharePoint API timeout — document not synced.' Errors started 3 days ago. SharePoint site is accessible via browser. The sync service account password expired (90-day rotation policy). The sync process uses a service account to authenticate to SharePoint Online via OAuth2.",
                "decision_made": "The SharePoint sync service account password expired, causing OAuth2 token refresh failures. Need to reset the password, update the sync configuration, and reprocess stuck documents.",
                "technical_detail": "-- Check documents with sync errors\nSELECT doc_id, project_id, doc_type, title,\n       sync_status, sync_error, uploaded_at\nFROM eb_document\nWHERE sync_status = 'ERROR'\nORDER BY uploaded_at DESC;\n\n-- Count by project\nSELECT project_id, COUNT(*) AS stuck_docs\nFROM eb_document\nWHERE sync_status = 'ERROR'\nGROUP BY project_id;\n\n-- The sync uses OAuth2 with service account:\n-- Client ID: eb-sync-client\n-- Scope: Sites.ReadWrite.All\n-- Token endpoint: login.microsoftonline.com/{tenant}/oauth2/v2.0/token\n-- Error: 'invalid_grant: AADSTS50076: password expired'",
                "sql_or_config": "# Step 1: Reset service account password in Azure AD\n# Azure Portal > Azure Active Directory > Users\n# eb-sync-service@cctx.onmicrosoft.com > Reset Password\n\n# Step 2: Update e-Builder sync configuration\n# e-Builder Admin > Documents > Sync Settings\n# Update service account password\n# Test Connection > ✓ Success\n\n# Step 3: Reprocess stuck documents\nUPDATE eb_document\nSET sync_status = 'PENDING'\nWHERE sync_status = 'ERROR';\n\n# Step 4: Trigger manual sync\n# e-Builder Admin > Documents > Sync Now\n\n# Step 5: Verify sync success\nSELECT sync_status, COUNT(*) AS doc_count\nFROM eb_document\nGROUP BY sync_status;\n-- Expected: all SYNCED, zero ERROR\n\n# Step 6: Prevention — set up password expiry alert\n# PowerShell:\n# $user = Get-AzureADUser -ObjectId 'eb-sync-service@cctx.onmicrosoft.com'\n# $expiry = $user.PasswordPolicies\n# If expiry within 14 days, send alert email",
                "why_correct": "Service account password expiration is one of the most common causes of integration failures in organizations that use Microsoft 365 / Azure AD. The OAuth2 token refresh fails when the underlying password expires, even if the current access token hasn't expired yet. The fix is straightforward: reset the password and update the config. The prevention is either: (1) Set the service account to 'Password never expires' (if security policy allows), (2) Use certificate-based authentication instead of passwords, or (3) Implement a monitoring script that alerts before password expiration.",
                "what_to_document": "1. Incident: INC-2026-0164 — 34 documents stuck in e-Builder-to-SharePoint sync\n2. Root cause: Service account password expired (90-day rotation policy)\n3. Fix: Reset password, updated config, reprocessed 34 documents\n4. Prevention: Certificate-based auth recommended (no password expiry)\n5. Runbook: e-Builder SharePoint Sync — Troubleshooting Guide",
                "what_to_test": "1. Verify all 34 documents now show sync_status = 'SYNCED'\n2. Spot-check 3 documents in SharePoint — verify they are accessible\n3. Upload a new test document and verify it syncs within 5 minutes\n4. Verify field inspectors can access documents on mobile\n5. Monitor sync for 24 hours for any new failures",
                "mentor_explanation": "Document management integrations between project management tools and collaboration platforms (like SharePoint) are increasingly common in municipal IT. The challenge is that these integrations rely on service accounts with credentials that expire. When they do, the integration fails silently until someone notices documents are missing. The best practice is to use certificate-based authentication (which doesn't expire as frequently) or implement proactive monitoring. In the field, this is the kind of issue that seems small but has a big impact — construction inspectors without access to current drawings can't do their jobs safely.",
                "interview_answer": "STAR: Situation — 34 construction documents were stuck in the e-Builder-to-SharePoint sync queue, preventing field engineers and inspectors from accessing current project documents. Task — Diagnose the sync failure, restore document access, and prevent recurrence. Action — Identified the root cause as an expired service account password causing OAuth2 token refresh failures. Reset the password in Azure AD, updated the e-Builder sync configuration, and reprocessed all 34 stuck documents. Verified documents were accessible in SharePoint and on mobile devices. Result — All documents synced within 30 minutes of the password reset. Recommended migrating to certificate-based authentication to eliminate password expiry as a failure mode. Created a monitoring script to alert 14 days before credential expiration.",
                "skills_practiced": "web_services,sharepoint,powershell,debugging,process_docs",
                "phase": "investigation",
            },
        ],
    },
}
